[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redireciona todas as rotas para o index.html (aplicação SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
